apiVersion: ignite.weave.works/v1alpha1
kind: VM
metadata:
  name: ubuntu-vm
  uid: 05286f8fb73dc324
spec:
  cpus: 2
  diskSize: 4GB
  memory: 1GB
  image:
    ociClaim:
      ref: weaveworks/ignite-ubuntu:latest
  kernel:
    ociClaim:
      ref: weaveworks/ignite-kernel:4.19.47
  ssh: true
status:
  state: Created
